# Generated by Django 5.2.2 on 2025-06-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnHandBalanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.TextField()),
                ('location', models.CharField(max_length=50)),
                ('warehouse', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=20)),
                ('Commodity', models.CharField(max_length=200)),
                ('name', models.TextField()),
                ('gl_acount', models.DecimalField(decimal_places=0, max_digits=15)),
                ('storage_on_hand', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=10)),
                ('allocated', models.DecimalField(decimal_places=0, max_digits=10)),
                ('available', models.DecimalField(decimal_places=0, max_digits=10)),
                ('uom', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=6, max_digits=19)),
                ('value', models.DecimalField(decimal_places=6, max_digits=19)),
                ('aisle', models.CharField(max_length=20)),
                ('bin', models.DecimalField(decimal_places=0, max_digits=19)),
                ('level', models.DecimalField(decimal_places=0, max_digits=10)),
                ('created_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Onhand Balance',
                'verbose_name_plural': 'Onhand Balances',
                'db_table': 'onhand_balances',
            },
        ),
        migrations.CreateModel(
            name='ProjectedObsolescence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('item_number', models.TextField()),
                ('item_name', models.CharField(max_length=255)),
                ('lot_number', models.CharField(max_length=100)),
                ('expiration_date', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=10)),
                ('uom', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=6, max_digits=19)),
                ('value', models.DecimalField(decimal_places=6, max_digits=19)),
            ],
            options={
                'verbose_name': 'Projected Obsolescence',
                'verbose_name_plural': 'Projected Obsolescences',
                'db_table': 'projected_obsolescence',
            },
        ),
    ]
