# Generated by Django 5.2.2 on 2025-06-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=19)),
                ('warehouse', models.CharField(max_length=100)),
                ('number_of_lines', models.DecimalField(decimal_places=0, max_digits=19)),
                ('total_value', models.DecimalField(decimal_places=6, max_digits=19)),
                ('currency', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date', models.CharField(max_length=20)),
                ('discrepancy_lines', models.DecimalField(decimal_places=0, max_digits=19)),
                ('status', models.CharField(max_length=20)),
                ('percentage', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Cycle Count',
                'verbose_name_plural': 'Cycle Counts',
                'db_table': 'cycle_count',
            },
        ),
    ]
