# Generated by Django 5.2.2 on 2025-06-17 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_cyclecount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cyclecount',
            old_name='price',
            new_name='cycle_count',
        ),
    ]
