# Generated by Django 5.2.2 on 2025-06-20 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_carryingcost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carryingcost',
            old_name='Damage',
            new_name='damage',
        ),
        migrations.RenameField(
            model_name='carryingcost',
            old_name='Handling',
            new_name='handling',
        ),
        migrations.RenameField(
            model_name='carryingcost',
            old_name='Loss',
            new_name='loss',
        ),
        migrations.RenameField(
            model_name='carryingcost',
            old_name='Storage',
            new_name='storage',
        ),
        migrations.RemoveField(
            model_name='carryingcost',
            name='cycle_count',
        ),
    ]
