# Generated by Django 5.2.2 on 2025-06-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rename_damage_carryingcost_damage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryOutstanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('active', models.CharField(max_length=100)),
                ('inventory_oustanding', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Inventory Outstanding',
                'verbose_name_plural': 'Inventory Outstandings',
                'db_table': 'inventory_outstanding',
            },
        ),
    ]
