# Generated by Django 5.2.2 on 2025-06-20 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventoryoutstanding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryoutstanding',
            old_name='inventory_oustanding',
            new_name='inventory_outstanding',
        ),
    ]
