# Generated by Django 5.2.2 on 2025-06-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_rename_inventory_oustanding_inventoryoutstanding_inventory_outstanding'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryoutstanding',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
