# Generated by Django 5.2.2 on 2025-06-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_inventoryoutstanding_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidInvoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=100)),
                ('req_number', models.CharField(max_length=100)),
                ('contract_punchout_user', models.CharField(max_length=255)),
                ('invoice_id', models.IntegerField()),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.CharField(max_length=100)),
                ('supplier', models.CharField(max_length=255)),
                ('total', models.DecimalField(decimal_places=2, max_digits=19)),
                ('payment_term', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('requester', models.CharField(max_length=100)),
                ('current_approver', models.CharField(max_length=100)),
                ('date_received', models.CharField(max_length=100)),
                ('created_date', models.CharField(max_length=100)),
                ('net_due_date', models.CharField(max_length=100)),
                ('discount_due_date', models.CharField(max_length=100)),
                ('payment_date', models.CharField(max_length=100)),
                ('epd_potential', models.CharField(max_length=100)),
                ('delivery_method', models.CharField(max_length=100)),
                ('pricing_bucket', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Paid Invoice',
                'verbose_name_plural': 'Paid Invoices',
                'db_table': 'paid_invoices',
            },
        ),
    ]
