# Generated by Django 5.2.2 on 2025-06-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_paidinvoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onhandbalancereport',
            name='bin',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='onhandbalancereport',
            name='level',
            field=models.CharField(max_length=50),
        ),
    ]
