# Generated by Django 5.2.2 on 2025-07-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_onhandbalancereport_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CpoPaidInvoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(blank=True, max_length=100, null=True)),
                ('req_number', models.CharField(blank=True, max_length=100, null=True)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('item', models.CharField(blank=True, max_length=255, null=True)),
                ('item_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('item_negotiated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('contract_punchout_user', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_id', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_date', models.DateTimeField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=255, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('payment_term', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('requester', models.CharField(blank=True, max_length=100, null=True)),
                ('current_approver', models.CharField(blank=True, max_length=100, null=True)),
                ('date_received_grn', models.DateTimeField(blank=True, null=True)),
                ('invoice_created_date', models.DateTimeField(blank=True, null=True)),
                ('net_due_date', models.DateTimeField(blank=True, null=True)),
                ('discount_due_date', models.DateTimeField(blank=True, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('epd_potential', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_method', models.CharField(blank=True, max_length=100, null=True)),
                ('pricing_bucket', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
