# Generated by Django 5.2.2 on 2025-07-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_cpopaidinvoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpopaidinvoices',
            name='contract_punchout_user',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cpopaidinvoices',
            name='current_approver',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cpopaidinvoices',
            name='delivery_method',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cpopaidinvoices',
            name='epd_potential',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cpopaidinvoices',
            name='invoice_id',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cpopaidinvoices',
            name='invoice_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cpopaidinvoices',
            name='item',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cpopaidinvoices',
            name='item_negotiated_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='cpopaidinvoices',
            name='item_unit_price',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='cpopaidinvoices',
            name='payment_term',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cpopaidinvoices',
            name='po_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cpopaidinvoices',
            name='pricing_bucket',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cpopaidinvoices',
            name='req_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cpopaidinvoices',
            name='requester',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cpopaidinvoices',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cpopaidinvoices',
            name='supplier',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cpopaidinvoices',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
    ]
