# Generated by Django 5.2.2 on 2025-07-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_cpopaidinvoices_contract_punchout_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadInventoryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('email', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
            ],
        ),
    ]
