# Generated by Django 5.2.2 on 2025-06-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('item_number', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=255)),
                ('lot_number', models.CharField(max_length=100)),
                ('expiration_date', models.CharField(max_length=20)),
                ('quantity', models.FloatField()),
                ('uom', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'inventory_items',
            },
        ),
    ]
